build:
  image: ensime/ensime:latest
  pull: true
  environment:
    - SONATYPE_USERNAME=$$SONATYPE_USERNAME
    - SONATYPE_PASSWORD=$$SONATYPE_PASSWORD
    - SCALA_VERSION=2.10.5
  commands:
    - sbt ++$SCALA_VERSION compile
    - if [ "$CI_REPO" = "ensime-sbt/master" ] ; then
        sbt ++$SCALA_VERSION publish ;
      fi
