build:
  image: ensime/ensime:latest
  pull: true
  environment:
    - SONATYPE_USERNAME=$$SONATYPE_USERNAME
    - SONATYPE_PASSWORD=$$SONATYPE_PASSWORD
    - SCALA_VERSION=2.10.6
  commands:
    - git log | head -n 20
    - sbt ++$SCALA_VERSION compile ;
      if [ $(git diff | wc -l) -ge 1 ] ; then
        echo "Code formatting does not meet the project's standards:" ;
        git --no-pager diff ;
        exit 1 ;
      fi
    - sbt ++$SCALA_VERSION scripted ;
    - if [ -z "$CI_PULL_REQUEST" ] ; then
        sbt ++$SCALA_VERSION publish ;
      fi
